---
tap_install:
  values:
    shared:
      ingress_domain: "tap-gitops.lab.khadilkar.net"
      image_registry:
        project_path: "index.docker.io/ykhadilkar"
      kubernetes_distribution: ""

      kubernetes_version: "1.24.9" # Required regardless of distribution when Kubernetes version is 1.25 or later.


    ceip_policy_disclosed: true # Installation fails if this is not set to true. Not a string.

    excluded_packages:
      - learningcenter.tanzu.vmware.com
      - workshops.learningcenter.tanzu.vmware.com
      - tap-telemetry.tanzu.vmware.com
      - carbonblack.scanning.apps.tanzu.vmware.com

    #The above keys are minimum numbers of entries needed in tap-values.yaml to get a functioning TAP Full profile installation.

    #Below are the keys which may have default values set, but can be overridden.

    profile: full # Can take iterate, build, run, view.

    supply_chain: basic # Can take testing, testing_scanning.

    ootb_supply_chain_basic: # Based on supply_chain set above, can be changed to ootb_supply_chain_testing, ootb_supply_chain_testing_scanning.
      registry:
        server: "index.docker.io" # Takes the value from the shared section by default, but can be overridden by setting a different value.
        repository: "ykhadilkar" # Takes the value from the shared section by default, but can be overridden by setting a different value.
      gitops:
        ssh_secret: "" # Takes "" as value by default; but can be overridden by setting a different value.

    contour:
      envoy:
        service:
          type: LoadBalancer # This is set by default, but can be overridden by setting a different value.

    buildservice:
      # Takes the value from the shared section by default, but can be overridden by setting a different value.
      kp_default_repository: "ykhadilkar/build-service"
      # kp_default_repository_secret: # Takes the value from the shared section above by default, but can be overridden by setting a different value.
        # name: "KP-DEFAULT-REPO-SECRET"
        # namespace: "KP-DEFAULT-REPO-SECRET-NAMESPACE"

    tap_gui:
      service_type: ClusterIP # If the shared.ingress_domain is set as earlier, this must be set to ClusterIP.
      metadataStoreAutoconfiguration: true # Create a service account, the Kubernetes control plane token and the requisite app_config block to enable communications between Tanzu Application Platform GUI and SCST - Store.
      app_config:
        catalog:
          locations:
            - type: url
              target: https://github.com/ykhadilkar/tanzu-java-web-app/blob/main/catalog/catalog-info.yaml

    metadata_store:
      ns_for_export_app_cert: "default"
      app_service_type: ClusterIP # Defaults to LoadBalancer. If shared.ingress_domain is set earlier, this must be set to ClusterIP.

    scanning:
      metadataStore:
        url: "" # Configuration is moved, so set this string to empty.

    grype:
      namespace: "default"
      # targetImagePullSecret: "tap-registry"
      # In a single cluster, the connection between the scanning pod and the metadata store happens inside the cluster and does not pass through ingress. This is automatically configured, you do not need to provide an ingress connection to the store.

    policy:
      tuf_enabled: false # By default, TUF initialization and keyless verification are deactivated.
